apiVersion: v1
kind: Secret
metadata:
  name: llm-secrets
type: Opaque
stringData:
  openai_api_key: "your-openai-key"
  hf_api_key: "your-hf-key"
  groq_api_key: "your-groq-key"
  gateway_api_key: "your-gateway-api-key"